DROP TABLE IF EXISTS city_country CASCADE;
DROP TABLE IF EXISTS country_continent CASCADE;
DROP TABLE IF EXISTS country CASCADE;
DROP TABLE IF EXISTS city CASCADE;
DROP TABLE IF EXISTS continent CASCADE;